- name: Symbolic link .config/nvim
  ansible.builtin.file:
    state: link
    src: "{{ role_path }}/files/nvim"
    dest: "{{ ansible_facts['env'].HOME }}/.config/nvim"
    force: true

# Lazy Commands Docs: https://lazy.folke.io/usage#-commands
- name: Lock Neovim Plugins
  ansible.builtin.command: nvim --headless "+Lazy! restore" +qa
  register: lazy_restore_cmd
  changed_when: "lazy_restore_cmd.stdout_lines | select('search', 'switching') | length != 0"
  # A branch "switch" is only done when a new plugin is installed or an existing plugin is updated to point to another commit.

- name: Clean Neovim Plugins
  ansible.builtin.command: nvim --headless "+Lazy! clean" +qa
  register: lazy_clean_cmd
  changed_when: "lazy_clean_cmd.stdout_lines | length != 0"
