homebrew_formulas:
  all:
    - neovim
    - git
    - gh
    - bash
    - bash-completion@2
    - jq
    - yq
    - fzf
    - fnm
    - kubectl
    - tree-sitter-cli
    - ripgrep
    - node
    - yarn
    - worktrunk
  work:
    - chainsaw
    - p6m
    - acli
