- name: Copy .gitignore
  ansible.builtin.copy:
    src: ".gitignore"
    dest: "{{ ansible_facts['env'].HOME }}/.gitignore"
    mode: "0644"

- name: Template .gitconfig
  ansible.builtin.template:
    src: ".gitconfig.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.gitconfig"
    mode: "0644"

- name: Symbolic link .gitconfig.d
  ansible.builtin.file:
    src: "{{ role_path }}/files/.gitconfig.d"
    path: "{{ ansible_facts['env'].HOME }}/.gitconfig.d"
    state: link
    force: true
