- name: Copy zprofile
  ansible.builtin.copy:
    src: ".zprofile"
    dest: "{{ ansible_facts['env'].HOME }}/.zprofile"

- name: Create zsh plugins directory
  ansible.builtin.file:
    path: "{{ ansible_facts['env'].HOME }}/.zsh/plugins/"
    state: directory

- name: Download nvm install plugin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/lukechilds/zsh-nvm/745291dcf20686ec421935f1c3f8f3a2918dd106/zsh-nvm.plugin.zsh
    dest: "{{ ansible_facts['env'].HOME }}/.zsh/plugins/"

- name: Template zshrc
  ansible.builtin.template:
    src: ".zshrc.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.zshrc"
