- name: Install packages (Homebrew)
  when: ansible_facts['distribution'] == "MacOSX"
  block:
    - name: Install formulas
      ansible.builtin.package:
        state: present
        name:
          - neovim
          - git
          - gh
          - bash
          - jq
          - yq
          - fzf
          - claude-code@latest
          - fnm
          - kubectl
          - tree-sitter-cli
          - ripgrep
    # TODO: Configure taps, casks, etc.

- name: Install packages (Arch)
  when: ansible_facts['distribution'] == "Archlinux"
  become: "{{ not ansible_check_mode }}"
  block:
    - name: Install packages
      ansible.builtin.package:
        state: present
        name:
          - neovim
          - git
          - github-cli
          - bash
          - jq
          - go-yq
          - fzf
          - fnm
          - tree-sitter
          - rg
    # TODO: Install from AUR?

- name: Gather fnm info
  ansible.builtin.command: fnm list
  register: fnm_list
  changed_when: false

- name: Install node LTS
  ansible.builtin.command: fnm install --lts
  changed_when: "fnm_list.stdout_lines | select('search', 'lts-latest') | length == 0"

- name: Set node LTS as default
  ansible.builtin.command: fnm default lts-latest
  changed_when: "fnm_list.stdout_lines | select('search', 'lts-latest') | select('search', 'default') | length == 0"
# TODO: Install claude-code with native curl script (use checksums and code signing). Remove from homebrew
# TODO: Install yarn with fnm
