- name: Install packages (Homebrew)
  when: ansible_facts['distribution'] == "MacOSX"
  block:
    # TODO: Configure taps
    - name: Install formulas
      community.general.homebrew:
        state: present
        name:
          - neovim
          - git
          - gh
          - bash
          - jq
          - yq
          - fzf
          - claude-code@latest
          - fnm
          - kubectl
          - tree-sitter-cli
          - ripgrep
          - node
          - yarn
          - worktrunk
    - name: Install casks
      community.general.homebrew_cask:
        state: present
        name:
          - font-jetbrains-mono-nerd-font
          - font-fira-code-nerd-font

- name: Install packages (Arch)
  when: ansible_facts['distribution'] == "Archlinux"
  become: "{{ not ansible_check_mode }}"
  block:
    - name: Install packages
      community.general.pacman:
        state: present
        name:
          - neovim
          - git
          - github-cli
          - bash
          - jq
          - go-yq
          - fzf
          - fnm
          - timeshift
          - tree-sitter
          - ripgrep
          - nodejs
          - npm
          - yarn
          - worktrunk
          - ttf-firacode-nerd
          - ttf-jetbrains-mono-nerd
    # TODO: Install from AUR?

- name: Gather fnm info
  ansible.builtin.command: fnm list
  register: fnm_list
  check_mode: false
  changed_when: false

- name: Set system node as default
  ansible.builtin.command: "{% if ansible_check_mode %}echo{% else %}fnm default system{% endif %}"
  check_mode: false
  changed_when: "fnm_list.stdout_lines | select('search', 'system') |
    select('search', 'default') | length == 0"
# TODO: Install claude-code with native curl script (use checksums and code signing). Remove from homebrew
