- name: Template .profile
  ansible.builtin.template:
    src: ".profile.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.profile"

- name: Template .aliases
  ansible.builtin.template:
    src: ".aliases.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.aliases"
