# Lazy Commands Docs: https://lazy.folke.io/usage#-commands
- name: restore neovim plugins
  ansible.builtin.command: nvim --headless "+Lazy! restore" +qa
- name: clean neovim plugins
  ansible.builtin.command: nvim --headless "+Lazy! clean" +qa
- name: install neovim plugins
  ansible.builtin.command: nvim --headless "+Lazy! install" +qa
- name: writeback neovim lockfile
  ansible.builtin.copy:
    src: "{{ ansible_facts['env'].HOME }}/.config/nvim/lazy-lock.json"
    dest: "{{ role_path }}/files/nvim/lazy-lock.json"
    mode: "0644"
