# TODO: Install bash
# TODO: Ensure bash is set as default shell

- name: Copy bashprofile
  ansible.builtin.template:
    src: ".bash_profile.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.bash_profile"

- name: Template bashrc
  ansible.builtin.template:
    src: ".bashrc.j2"
    dest: "{{ ansible_facts['env'].HOME }}/.bashrc"
