vim.g.mapleader = " "
vim.g.maplocalleader = ";"
vim.o.number = true -- TODO: Do not show on oil
vim.o.scrolloff = 8
vim.o.tabstop = 8
vim.o.softtabstop = -1
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.autoindent = true
vim.o.smartindent = true
vim.o.mouse = ""
