- name: Setup Neovim
  ansible.builtin.include_role:
    name: nvim
  tags: [neovim]

- name: Setup Git
  ansible.builtin.include_role:
    name: git
  tags: [git]

- name: Setup Claude Code
  ansible.builtin.include_role:
    name: claude-code
  tags: [claude-code]

- name: Setup Bash
  ansible.builtin.include_role:
    name: bash
  tags: [bash]
  when: "'bash' in ansible_facts['env'].SHELL or bash_check.rc == 0"

