- name: Setup Neovim
  ansible.builtin.import_role:
    name: nvim
  tags: [neovim]

- name: Setup Git
  ansible.builtin.import_role:
    name: git
  tags: [git]

- name: Setup Claude Code
  ansible.builtin.import_role:
    name: claude-code
  tags: [claude-code]

- name: Setup Bash
  ansible.builtin.import_role:
    name: bash
  tags: [bash]
